filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"
