apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: project-secrets
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: project-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: secret/data/project/config
      property: POSTGRES_PASSWORD
