apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
data:
  APP_NAME: "project-api"
  LOG_LEVEL: "info"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "project_db"
  REDIS_ADDR: "redis:6379"
  KAFKA_BROKERS: "kafka:9092"
