global:
  scrape_interval: 2s 

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8080']

  - job_name: 'worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:9092']

  - job_name: 'consumer'
    metrics_path: /metrics
    static_configs:
      - targets: ['consumer:9091']
